### PR TITLE
deployment history

### PR DESCRIPTION
**Pull request by jacyzon**
Mockup:
selection_004

---

20150626 Update:

screenshot_2015-06-25_23-57-49

### CODE REVIEW

**Comment by lukebond** [comment]
Let's put further visual work on this on hold until @jongold has time to take a look at it and give feedback.

**Comment by lukebond** [comment]
A few non-visual comments:
- What's the Deployment | Config toggle at the top for?
- What's the padlock button for?
- I don't want the history grouped by service, but to be a linear history of deployments.
- Given I don't want it grouped by service, the columns would probably be: Date/Time, Service Name and Version followed by the config used for the deployment: Public Facing, Ports, Env Vars and Num Instances. Depending on the amount of space available the config may need to go on a separate line

**Comment by jacyzon** [comment]
> What's the Deployment | Config toggle at the top for?

plan to toggle the view for config history

https://github.com/paz-sh/paz-orchestrator/blob/master/docs/api-blueprint.md#config-history-servicesnameconfighistory

> What's the padlock button for?

show/hide env values using asterisks

> I don't want the history grouped by service, but to be a linear history of deployments.
> Given I don't want it grouped by service, the columns would probably be: Date/Time, Service Name and Version followed by the config used for the deployment: Public Facing, Ports, Env Vars and Num Instances. Depending on the amount of space available the config may need to go on a separate line

okay, I can do that.

**Comment by lukebond** [comment]
> plan to toggle the view for config history

do you mean to switch between viewing the history of config changes vs the history of deployments? the latter is all that I'm interested in showing here, because you can change config as much as you like but it isn't actually used until you next deploy, so I want to show a deployment history along with the config that was used at each deploy/version.

i think a good place to start for this feature is paz-sh/paz-scheduler#10 and paz-sh/paz-scheduler#11, because once the data model is clear the rest will fall into place and will be obvious. unfortunately this is the stuff I was working on and then lost :(

**Comment by jacyzon** [comment]
Yes, so both history of config and history of deployments can be displayed in same page, if the config has not been deployed then it can be edit by the user, right?

**Comment by lukebond** [comment]
the config is already editable on the Services tab.

the sole aim of this history tab is the deployment history, so an admin can come and see what's happened, like a log or journal. the admin will want to know what was deployed and when, and with what config.

there is no need to see the history of config in any other way.

does that make sense?

note that in my notes in paz-sh/paz-scheduler#10 i'm suggesting a journal entry be a lookup into the existing deployment records, the "journal" keys are simply an index. this tab simply scans that index, looks up each deploy record and displays the fields i've listed above.

**Comment by jacyzon** [comment]
:thumbsup:

**Comment by jacyzon** [comment]
quick update here:
selection_006

I think the arrangement is a bit messy, what if it only shows one config one time (click the service row and the config get expanded)

@lukebond Any ideas?

**Comment by lukebond** [comment]
Thanks for iterating on this @jacyzon, I'm aware I could have defined this task more clearly for you!

I'll leave aesthetics to @jongold (probably over the weekend during the hackathon), but all the data I want to see is there.

I agree it's a bit messy, perhaps showing no config line at all until you click to expand would be the best approach. But aesthetics are not my _forte_ so let's wait and see what Jon says.

You can drop the "User" column. Perhaps reserve it for a "Success" true/false field (not currently available). Someday we'd like to know the user of the Paz UI that deployed it, but we don't have such a thing today. Unit files will specify the "core" user but that's irrelevant- it's the Unix user that systemd will launch the service as.

**Comment by lukebond** [comment]
@jacyzon let's not wait for aesthetic feedback on this.

does the above represent the current visuals? if not LMK with another mockup and perhaps we can proceed.

**Comment by jacyzon** [comment]
@lukebond 
Done~
Pls have a see =)

**Comment by lukebond** [comment]
Given the sass dependency issue I'm unable to build and see this. Any chance you could post a screenshot @jacyzon ?

**Comment by jacyzon** [comment]
Please see the updated PR message.

**Comment by lukebond** [comment]
@jacyzon looking really nice! thanks :)

if i may suggest just two changes, but would appreciate your thoughts on them:
1. it may not be clear to the user that they can click on a row and it will expand to show the config; i can't tell from the screenshot of course, but do you have some sort of indicator on hover (perhaps a +/- or something, but you can click anywhere in the row to make it expand, not just on this symbol.
2. I'd prefer to combine the "Env key" and "Env value" columns into one "Env Vars" column, and list each in a row below as you do now, but perhaps as `key: value`?

What do you think?

**Comment by jacyzon** [comment]
Okay, make sense~
Please take a look at the updated version.

**Comment by lukebond** [comment]
i'm sorry would you mind posting a screenshot @jacyzon ?

**Comment by jacyzon** [comment]
Here you are~
screenshot_2015-06-28_21-37-49

**Comment by lukebond** [comment]
Thanks :) Yeah LGTM!

**Pull request merged**
