### PR TITLE
close #18 deploy button

### LINKED ISSUE #18: Add deploy button to UI
If you create a service in the service directory there is no way of deploying it without sending an HTTP POST to one of the scheduler deploy endpoints. It would be good to have a button in the UI somewhere.

In the "Services" section perhaps, once you've clicked to view a particular service?

### PR DESCRIPTION
**Pull request by jacyzon**

### CODE REVIEW

**Comment by lukebond** [comment]
Hey @jacyzon looks like you've been busy!

I took a look this evening and I'm happy with the solution but I found an issue. If I haven't deployed a service before then it seems to have a problem finding something by CSS selector (potentially wrong terminology!).

image

The problem seems to be here: https://github.com/jacyzon/paz-web/blob/6096336f359e41150385b723244c09dbb1046fa5/app/controllers/service.js#L27

Let me know if I'm missing something :/

**Comment by lukebond** [comment]
also I think this patch (not an actual patch!) is needed:

```
config/environment.js:
-      SCHEDULER_URL: process.env['PAZ_SCHEDULER_URL'] || 'http://localhost:9001'
+      SCHEDULER_URL: process.env['PAZ_SCHEDULER_URL'] || 'http://localhost:9002'
```

**Comment by jacyzon** [comment]
It is fixed.
The reason is that if the service has not been deployed, the last config can not get from server which cause configLast model being null, so the reload failed there.

I don't understand the difference between the port number 9001 and 9002?

**Comment by lukebond** [comment]
Port 9000 is the Orchestrator. 9001 the service directory and 9002 the scheduler.

**Comment by jacyzon** [comment]
ok, please have a look =)

**Pull request merged**
